image: mcr.microsoft.com/dotnet/core/sdk:3.1.101-alpine3.10

build:
  stage: build
  script: 
    - cd src
    - dotnet restore
    - dotnet build
  cache:
    policy: push
    paths:
      - src

test:
  stage: test
  script: 
    - cd src
    - dotnet test /p:CollectCoverage=true /p:Exclude='[xunit*]*'
  cache:
    policy: pull
    paths:
      - src
