image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic

build:
  stage: build
  script:
    - dotnet build --configuration Release-$QUANTUM_DEPTH src/ImageCasterCore
  parallel:
    matrix:
      - QUANTUM_DEPTH: [Q16-HDRI, Q16, Q8]

build-cross-platform:
  stage: build
  script:
    - dotnet publish --configuration Release-$QUANTUM_DEPTH src/$PROJECT
    - mv src/$PROJECT/bin/Release-$QUANTUM_DEPTH/netcoreapp3.1/publish/ imagecaster
  artifacts:
    paths:
      - imagecaster
  parallel:
    matrix:
      - QUANTUM_DEPTH: [Q16-HDRI, Q16, Q8]
        PROJECT: [ImageCasterCli, ImageCasterApi]

build-non-self-contained:
  stage: build
  script:
    - dotnet publish --configuration Release-$QUANTUM_DEPTH --runtime $RUNTIME --self-contained false src/$PROJECT
    - mv src/$PROJECT/bin/Release-$QUANTUM_DEPTH/netcoreapp3.1/$RUNTIME/publish/ imagecaster
  artifacts:
    paths:
      - imagecaster
  parallel:
    matrix:
      - QUANTUM_DEPTH: [Q16-HDRI, Q16, Q8]
        RUNTIME: [linux-x64, win-x64, osx-x64]
        PROJECT: [ImageCasterCli, ImageCasterApi]

build-self-contained:
  stage: build
  script:
    - dotnet publish --configuration Release-$QUANTUM_DEPTH --runtime $RUNTIME src/$PROJECT
    - mv src/$PROJECT/bin/Release-$QUANTUM_DEPTH/netcoreapp3.1/$RUNTIME/publish/ imagecaster
  artifacts:
    paths:
      - imagecaster
  parallel:
    matrix:
      - QUANTUM_DEPTH: [Q16-HDRI, Q16, Q8]
        RUNTIME: [linux-x64, win-x64, osx-x64]
        PROJECT: [ImageCasterCli, ImageCasterApi]

# Testing

test:
  stage: test
  script:
    - dotnet test --configuration Release-$QUANTUM_DEPTH src/ImageCasterCoreTest
  parallel:
    matrix:
      - QUANTUM_DEPTH: [Q16-HDRI, Q16, Q8]
