image: mcr.microsoft.com/dotnet/core/sdk:3.1.101-bionic

cache:
  paths:
    - src/*/bin/
    - src/*/obj/

build-q16-hdri:
  stage: build
  script: 
    - cd src
    - dotnet build --configuration Release-Q16-HDRI ImageCasterCore

build-q16:
  stage: build
  script: 
    - cd src
    - dotnet build --configuration Release-Q16 ImageCasterCore

build-q8:
  stage: build
  script: 
    - cd src
    - dotnet build --configuration Release-Q8 ImageCasterCore

test-q16-hdri:
  stage: test
  script: 
    - cd src
    - dotnet test --configuration Release-Q16-HDRI ImageCasterCoreTest
  cache:
    policy: pull

test-q16:
  stage: test
  script: 
    - cd src
    - dotnet test --configuration Release-Q16 ImageCasterCoreTest
  cache:
    policy: pull

test-q8:
  stage: test
  script: 
    - cd src
    - dotnet test --configuration Release-Q8 ImageCasterCoreTest
  cache:
    policy: pull
