image: mcr.microsoft.com/dotnet/core/sdk:3.1.101-alpine3.10

cache:
  paths:
    - src/*/bin/
    - src/*/obj/

build-q16-hdri:
  stage: build
  script: 
    - cd src
    - dotnet build --configuration Release-Q16-HDRI

build-q16:
  stage: build
  script: 
    - cd src
    - dotnet build --configuration Release-Q16

build-q8:
  stage: build
  script: 
    - cd src
    - dotnet build --configuration Release-Q8

test-q16-hdri:
  stage: test
  script: 
    - cd src
    - dotnet test --configuration Release-Q16-HDRI /p:Exclude='[xunit*]*'
  cache:
    policy: pull

test-q16:
  stage: test
  script: 
    - cd src
    - dotnet test --configuration Release-Q16 /p:Exclude='[xunit*]*'
  cache:
    policy: pull

test-q8:
  stage: test
  script: 
    - cd src
    - dotnet test --configuration Release-Q8 /p:Exclude='[xunit*]*'
  cache:
    policy: pull
