image: mcr.microsoft.com/dotnet/core/sdk:3.1.102-bionic

variables:
  CLI_PATH: src/ImageCasterCli/bin/Release-Q
  API_PATH: src/ImageCasterApi/bin/Release-Q
  NETCORE: netcoreapp3.1
  ARTIFACTS: publish/

# Build Library

build-q16-hdri:
  stage: build
  script: 
    - dotnet build --configuration Release-Q16-HDRI src/ImageCasterCore

build-q16:
  stage: build
  script: 
    - dotnet build --configuration Release-Q16 src/ImageCasterCore

build-q8:
  stage: build
  script: 
    - dotnet build --configuration Release-Q8 src/ImageCasterCore

# Non-Self-Contained Cross-Platform Builds

build-cli-q16-hdri:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI src/ImageCasterCli
    - mv ${CLI_PATH}16-HDRI/${NETCORE}/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q16:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 src/ImageCasterCli
    - mv ${CLI_PATH}16/${NETCORE}/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q8:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 src/ImageCasterCli
    - mv ${CLI_PATH}8/${NETCORE}/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-hdri:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI src/ImageCasterApi
    - mv ${API_PATH}16-HDRI/${NETCORE}/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 src/ImageCasterApi
    - mv ${API_PATH}16/${NETCORE}/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q8:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 src/ImageCasterApi
    - mv ${API_PATH}8/${NETCORE}/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

# Non-Self-Contained Linux Builds

build-cli-q16-hdri-linux:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI --runtime linux-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}16-HDRI/${NETCORE}/linux-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q16-linux:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 --runtime linux-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}16/${NETCORE}/linux-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q8-linux:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 --runtime linux-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}8/${NETCORE}/linux-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-hdri-linux:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI --runtime linux-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}16-HDRI/${NETCORE}/linux-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-linux:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 --runtime linux-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}16/${NETCORE}/linux-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q8-linux:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 --runtime linux-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}8/${NETCORE}/linux-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

# Non-Self-Contained Windows Builds

build-cli-q16-hdri-windows:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI --runtime win-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}16-HDRI/${NETCORE}/win-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q16-windows:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 --runtime win-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}16/${NETCORE}/win-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q8-windows:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 --runtime win-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}8/${NETCORE}/win-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-hdri-windows:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI --runtime win-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}16-HDRI/${NETCORE}/win-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-windows:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 --runtime win-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}16/${NETCORE}/win-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q8-windows:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 --runtime win-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}8/${NETCORE}/win-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

# Non-Self-Contained macOS Builds

build-cli-q16-hdri-mac:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI --runtime osx-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}16-HDRI/${NETCORE}/osx-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q16-mac:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 --runtime osx-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}16/${NETCORE}/osx-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-cli-q8-mac:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 --runtime osx-x64 --self-contained false src/ImageCasterCli
    - mv ${CLI_PATH}8/${NETCORE}/osx-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-hdri-mac:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16-HDRI --runtime osx-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}16-HDRI/${NETCORE}/osx-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q16-mac:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q16 --runtime osx-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}16/${NETCORE}/osx-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

build-api-q8-mac:
  stage: build
  script: 
    - dotnet publish --configuration Release-Q8 --runtime osx-x64 --self-contained false src/ImageCasterApi
    - mv ${API_PATH}8/${NETCORE}/osx-x64/${ARTIFACTS} public/
  artifacts:
    paths:
      - public/

# Testing

test-q16-hdri:
  stage: test
  script: 
    - dotnet test --configuration Release-Q16-HDRI src/ImageCasterCoreTest

test-q16:
  stage: test
  script: 
    - dotnet test --configuration Release-Q16 src/ImageCasterCoreTest

test-q8:
  stage: test
  script: 
    - dotnet test --configuration Release-Q8 src/ImageCasterCoreTest
