using System;
using System.Collections.Generic;
using System.Linq;
using ImageMagick;

namespace ImageCasterCore.Utilities
{
    /// <summary>Static utility methods for the ExifTag object.</summary>
    public static class ExifUtils
    {
        /// <summary>
        /// A list of all valid Exif tags.
        /// This list is manually collated from the underlying objects in Magick.NET.
        /// </summary>
        public static readonly List<ExifTag> Tags = new List<ExifTag>()
        {
            ExifTag.FaxProfile,
            ExifTag.ModeNumber,
            ExifTag.GPSAltitudeRef,
            ExifTag.ClipPath,
            ExifTag.VersionYear,
            ExifTag.XMP,
            ExifTag.CFAPattern2,
            ExifTag.TIFFEPStandardID,
            ExifTag.XPTitle,
            ExifTag.XPComment,
            ExifTag.XPAuthor,
            ExifTag.XPKeywords,
            ExifTag.XPSubject,
            ExifTag.GPSVersionID,
            ExifTag.PixelScale,
            ExifTag.IntergraphMatrix,
            ExifTag.ModelTiePoint,
            ExifTag.ModelTransform,
            ExifTag.SubfileType,
            ExifTag.SubIFDOffset,
            ExifTag.GPSIFDOffset,
            ExifTag.T4Options,
            ExifTag.T6Options,
            ExifTag.XClipPathUnits,
            ExifTag.YClipPathUnits,
            ExifTag.ProfileType,
            ExifTag.CodingMethods,
            ExifTag.T82ptions,
            ExifTag.JPEGInterchangeFormat,
            ExifTag.JPEGInterchangeFormatLength,
            ExifTag.MDFileTag,
            ExifTag.StandardOutputSensitivity,
            ExifTag.RecommendedExposureIndex,
            ExifTag.ISOSpeed,
            ExifTag.ISOSpeedLatitudeyyy,
            ExifTag.ISOSpeedLatitudezzz,
            ExifTag.FaxRecvParams,
            ExifTag.FaxRecvTime,
            ExifTag.ImageNumber,
            ExifTag.FreeOffsets,
            ExifTag.FreeByteCounts,
            ExifTag.ColorResponseUnit,
            ExifTag.TileOffsets,
            ExifTag.SMinSampleValue,
            ExifTag.SMaxSampleValue,
            ExifTag.JPEGQTables,
            ExifTag.JPEGDCTables,
            ExifTag.JPEGACTables,
            ExifTag.StripRowCounts,
            ExifTag.IntergraphRegisters,
            ExifTag.TimeZoneOffset,
            ExifTag.ImageWidth,
            ExifTag.ImageLength,
            ExifTag.TileWidth,
            ExifTag.TileLength,
            ExifTag.BadFaxLines,
            ExifTag.ConsecutiveBadFaxLines,
            ExifTag.PixelXDimension,
            ExifTag.PixelYDimension,
            ExifTag.StripOffsets,
            ExifTag.TileByteCounts,
            ExifTag.ImageLayer,
            ExifTag.XPosition,
            ExifTag.YPosition,
            ExifTag.XResolution,
            ExifTag.YResolution,
            ExifTag.BatteryLevel,
            ExifTag.ExposureTime,
            ExifTag.FNumber,
            ExifTag.MDScalePixel,
            ExifTag.CompressedBitsPerPixel,
            ExifTag.ApertureValue,
            ExifTag.MaxApertureValue,
            ExifTag.SubjectDistance,
            ExifTag.FocalLength,
            ExifTag.FlashEnergy2,
            ExifTag.FocalPlaneXResolution2,
            ExifTag.FocalPlaneYResolution2,
            ExifTag.ExposureIndex2,
            ExifTag.Humidity,
            ExifTag.Pressure,
            ExifTag.Acceleration,
            ExifTag.FlashEnergy,
            ExifTag.FocalPlaneXResolution,
            ExifTag.FocalPlaneYResolution,
            ExifTag.ExposureIndex,
            ExifTag.DigitalZoomRatio,
            ExifTag.GPSAltitude,
            ExifTag.GPSDOP,
            ExifTag.GPSSpeed,
            ExifTag.GPSTrack,
            ExifTag.GPSImgDirection,
            ExifTag.GPSDestBearing,
            ExifTag.GPSDestDistance,
            ExifTag.WhitePoint,
            ExifTag.PrimaryChromaticities,
            ExifTag.YCbCrCoefficients,
            ExifTag.ReferenceBlackWhite,
            ExifTag.GPSLatitude,
            ExifTag.GPSLongitude,
            ExifTag.GPSTimestamp,
            ExifTag.GPSDestLatitude,
            ExifTag.GPSDestLongitude,
            ExifTag.LensInfo,
            ExifTag.OldSubfileType,
            ExifTag.Compression,
            ExifTag.PhotometricInterpretation,
            ExifTag.Thresholding,
            ExifTag.CellWidth,
            ExifTag.CellLength,
            ExifTag.FillOrder,
            ExifTag.Orientation,
            ExifTag.SamplesPerPixel,
            ExifTag.PlanarConfiguration,
            ExifTag.GrayResponseUnit,
            ExifTag.ResolutionUnit,
            ExifTag.CleanFaxData,
            ExifTag.InkSet,
            ExifTag.NumberOfInks,
            ExifTag.DotRange,
            ExifTag.Indexed,
            ExifTag.OPIProxy,
            ExifTag.JPEGProc,
            ExifTag.JPEGRestartInterval,
            ExifTag.YCbCrPositioning,
            ExifTag.Rating,
            ExifTag.RatingPercent,
            ExifTag.ExposureProgram,
            ExifTag.Interlace,
            ExifTag.SelfTimerMode,
            ExifTag.SensitivityType,
            ExifTag.MeteringMode,
            ExifTag.LightSource,
            ExifTag.FocalPlaneResolutionUnit2,
            ExifTag.SensingMethod2,
            ExifTag.Flash,
            ExifTag.ColorSpace,
            ExifTag.FocalPlaneResolutionUnit,
            ExifTag.SensingMethod,
            ExifTag.CustomRendered,
            ExifTag.ExposureMode,
            ExifTag.WhiteBalance,
            ExifTag.FocalLengthIn35mmFilm,
            ExifTag.SceneCaptureType,
            ExifTag.GainControl,
            ExifTag.Contrast,
            ExifTag.Saturation,
            ExifTag.Sharpness,
            ExifTag.SubjectDistanceRange,
            ExifTag.GPSDifferential,
            ExifTag.BitsPerSample,
            ExifTag.MinSampleValue,
            ExifTag.MaxSampleValue,
            ExifTag.GrayResponseCurve,
            ExifTag.ColorMap,
            ExifTag.ExtraSamples,
            ExifTag.PageNumber,
            ExifTag.TransferFunction,
            ExifTag.Predictor,
            ExifTag.HalftoneHints,
            ExifTag.SampleFormat,
            ExifTag.TransferRange,
            ExifTag.DefaultImageColor,
            ExifTag.JPEGLosslessPredictors,
            ExifTag.JPEGPointTransforms,
            ExifTag.YCbCrSubsampling,
            ExifTag.CFARepeatPatternDim,
            ExifTag.IntergraphPacketData,
            ExifTag.ISOSpeedRatings,
            ExifTag.SubjectArea,
            ExifTag.SubjectLocation,
            ExifTag.ShutterSpeedValue,
            ExifTag.BrightnessValue,
            ExifTag.ExposureBiasValue,
            ExifTag.AmbientTemperature,
            ExifTag.WaterDepth,
            ExifTag.CameraElevationAngle,
            ExifTag.Decode,
            ExifTag.ImageDescription,
            ExifTag.Make,
            ExifTag.Model,
            ExifTag.Software,
            ExifTag.DateTime,
            ExifTag.Artist,
            ExifTag.HostComputer,
            ExifTag.Copyright,
            ExifTag.DocumentName,
            ExifTag.PageName,
            ExifTag.InkNames,
            ExifTag.TargetPrinter,
            ExifTag.ImageID,
            ExifTag.MDLabName,
            ExifTag.MDSampleInfo,
            ExifTag.MDPrepDate,
            ExifTag.MDPrepTime,
            ExifTag.MDFileUnits,
            ExifTag.SEMInfo,
            ExifTag.SpectralSensitivity,
            ExifTag.DateTimeOriginal,
            ExifTag.DateTimeDigitized,
            ExifTag.SubsecTime,
            ExifTag.SubsecTimeOriginal,
            ExifTag.SubsecTimeDigitized,
            ExifTag.RelatedSoundFile,
            ExifTag.FaxSubaddress,
            ExifTag.OffsetTime,
            ExifTag.OffsetTimeOriginal,
            ExifTag.OffsetTimeDigitized,
            ExifTag.SecurityClassification,
            ExifTag.ImageHistory,
            ExifTag.ImageUniqueID,
            ExifTag.OwnerName,
            ExifTag.SerialNumber,
            ExifTag.LensMake,
            ExifTag.LensModel,
            ExifTag.LensSerialNumber,
            ExifTag.GDALMetadata,
            ExifTag.GDALNoData,
            ExifTag.GPSLatitudeRef,
            ExifTag.GPSLongitudeRef,
            ExifTag.GPSSatellites,
            ExifTag.GPSStatus,
            ExifTag.GPSMeasureMode,
            ExifTag.GPSSpeedRef,
            ExifTag.GPSTrackRef,
            ExifTag.GPSImgDirectionRef,
            ExifTag.GPSMapDatum,
            ExifTag.GPSDestLatitudeRef,
            ExifTag.GPSDestLongitudeRef,
            ExifTag.GPSDestBearingRef,
            ExifTag.GPSDestDistanceRef,
            ExifTag.GPSDateStamp,
            ExifTag.JPEGTables,
            ExifTag.OECF,
            ExifTag.ExifVersion,
            ExifTag.ComponentsConfiguration,
            ExifTag.MakerNote,
            ExifTag.UserComment,
            ExifTag.FlashpixVersion,
            ExifTag.SpatialFrequencyResponse,
            ExifTag.SpatialFrequencyResponse2,
            ExifTag.Noise,
            ExifTag.CFAPattern,
            ExifTag.DeviceSettingDescription,
            ExifTag.ImageSourceData,
            ExifTag.GPSProcessingMethod,
            ExifTag.GPSAreaInformation,
            ExifTag.FileSource,
            ExifTag.SceneType
        };

        /// <param name="tagName">The Exif tag as a string literal.</param>
        /// <returns>The Exif tag specified by the user if found.</returns>
        /// <exception cref="ArgumentException">If the Exif tag specified doesn't exist.</exception>
        public static ExifTag FindByName(string tagName)
        {
            if (String.IsNullOrWhiteSpace(tagName))
            {
                return null;
            }

            ExifTag specifiedTag = Tags.Find((tag) =>
            {
                return String.Equals(tagName, tag.ToString(), StringComparison.CurrentCultureIgnoreCase);
            });

            return specifiedTag;
        }

        /// <returns>The names of all Exif tags.</returns>
        public static IEnumerable<string> GetNames()
        {
            return Tags.Select((tag) => tag.ToString());
        }
    }
}
